/**
 * The owner's photographs for the About page, supplied 2026-10-02 in
 * `public/Hazeberg/` (git-ignored: 204 MB of camera originals, never committed).
 *
 * The files served are the web copies in `public/about/`: EXIF-rotated, at
 * most 2000px on the long edge, JPEG at quality 80 (mozjpeg), metadata
 * stripped, 4.9 MB for all twenty-one. `next/image` sizes them from there.
 * `blur` is a 16px WebP of the same frame, for `placeholder="blur"`.
 *
 * Alt text describes the moment, not the faces: these are real people, and
 * only the names the owner put on the files are used.
 *
 * Generated by the scratchpad script `photos.cjs` from the originals; re-run
 * it rather than editing a size by hand.
 */

export type AboutPhoto = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blur: string;
  /** The owner's original file in `public/Hazeberg/`. */
  source: string;
};

const photo = (name: string, width: number, height: number, alt: string, source: string, blur: string): AboutPhoto => ({
  src: `/about/${name}.jpg`,
  width,
  height,
  alt,
  blur,
  source,
});

export const PHOTOS = {
  "founder-portrait": photo("founder-portrait", 1536, 1024, "Sakthi Vignesh, Founder and CEO of Hazeberg Consulting, in a navy suit in the office", "Founder Photo.png", "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwAgCdASoQAAsAAsBMJZgCdAYwna9SubcQQAD9nW8+l7Q7OjrvqQHf+8H2wl51l7ACrENZjlp3nLsjwIjO5FQ21RWn4t7hyr3spUAPiS9P5mazn/LYOQPqQHv9M9YCPhfFoMJVd7jDD+SJ1OGTTZ4xoS5GTAAA"),
  "founder-recognition-01": photo("founder-recognition-01", 1280, 960, "Sakthi Vignesh with two guests at a recognition event", "Founder Recognization.jpeg", "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoQAAwAAsBMJQBOgCBvmVpqwAD++BdMy65dOd51bYuduF001CoKK1nPvTLfEJoWFVdxogcLE4ieKAceehHKjJXnFDB/aapCJ/ww8K6KNDALRBAXIGyKc2EAAAA="),
  "founder-recognition-02": photo("founder-recognition-02", 1148, 1280, "Sakthi Vignesh being presented with an award in an office", "Founder Recognization1.jpeg", "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADwAwCdASoQABIAPtFUo0uoJKMhsAgBABoJbACw7CBSLsN6qR/8XVMAAPlPfrsYphn/KlYwf164We8ALW2+u/gwHouG6zEgcVMAe+/ATYGxJGdR7h/hAs6X6AAobc6lYW/4lc02RHb8rHud7132sS77ya1D9kHPJVmLE/VS7n3jJ1hoYLxLhdquNOVjv9+lfyn5sEB5YjXzURyBasLYtVIAAAA="),
  "offsite-2025-01": photo("offsite-2025-01", 1600, 1200, "The team lined up along a riverside wall at the 2025 offsite", "Offsite 2025/WhatsApp Image 2026-10-02 at 11.50.52 AM (1).jpeg", "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAwAAsBMJZwAAqFbSRXkUAAA+GJgJwMGhEOyt+IZCcGqPT3WOZxXXuozHs+gtcdDTBBhrxRF04Jg6/sXs3F4Kvu+rJSLlLAgAA=="),
  "offsite-2025-02": photo("offsite-2025-02", 1200, 1600, "The team gathered in front of a wooden resort house at the 2025 offsite", "Offsite 2025/WhatsApp Image 2026-10-02 at 11.50.52 AM.jpeg", "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACwBACdASoQABUAPtFUo0uoJKMhsAgBABoJbACdMoAlsxlzD9S19ZAgabo8btdgAP7KVpOtfiDjKqDlrR8XSuj67aWWGWvkQsEJ8q2ePLu7juQE+5VcxBkPzOA/iM5B/sYBzG7y5khgCebTNDSL+LUcfcEdE+chOxjneh75d+L+9qAiB5B6AT9Sz/j/bpNk7dDZbwFyA7tunxODBGrySbmojyVKLsuK086nkH4zsZfJm6+pwxnzwe9DwAA="),
  "offsite-2025-03": photo("offsite-2025-03", 1200, 1600, "The team on a red path among the palms at the 2025 offsite", "Offsite 2025/WhatsApp Image 2026-10-02 at 11.50.53 AM (1).jpeg", "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAAAwBQCdASoQABUAPtFUo0uoJKMhsAgBABoJagCdOUB0meOgTgBQcCA7FMfFR4cRycC/gAD+43yE5sbakRXtPg3vyM6hrTVvWNgGbQC4/9KZ6sIz7DEpFMRyBLcqDkis9l8d7sWv2TOfgsf99mshPZrn6hWffeoypUAq4l5+RpRYy6iSq+lDNhK+TWDqHK3oQcSFlTWrOPwG57696VVi0boEAiTKGaFIlFRZ/BxjYUBT34GBiTNdF4e9Z6rSr+pPmeWk4++AAAA="),
  "offsite-2025-04": photo("offsite-2025-04", 1200, 1600, "The team around a cake under party lights, beside a sign that reads Hazeberg turns 1", "Offsite 2025/WhatsApp Image 2026-10-02 at 11.50.53 AM.jpeg", "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoQABUAPtFUo0uoJKMhsAgBABoJbACdMoCGACQbT01fZd0DAhqBcADidvKfEL3ev7fpYvuIcA3X2xN1GNJTbNasn1Q29YJzzQ450QlVopJpka6DlyLIbu2qTpJuzeo6oRGnc2TaMvDL9dDmvqlCrXktAF1OaE0zzULJeKIzm6n5H0aldrAAAA=="),
  "offsite-2026-01": photo("offsite-2026-01", 2000, 1333, "A team member laughing as she speaks into a microphone at the 2026 offsite", "Offsite 2026/JUN04805.JPG", "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQAAsAAsBMJaACdADRtErz2AAA3yvkFv6K7E65iRGk/+zrFPKWqALVbeRdWHnD0p0F1kHcbPbNr1hu5VFgTLa0O76KsEu+oW8K3z1iUruz/q5I8cKO3+AXAX6GzAAA"),
  "offsite-2026-02": photo("offsite-2026-02", 2000, 1333, "Team members seated together, laughing during a session at the 2026 offsite", "Offsite 2026/JUN04873.JPG", "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAsAAsBMJYwCdACxmRV0lIAA++O4nWSi72xXnG/dsS9PbwzRZFwWCUvNrdQcmgawpU0gFTeZDWE8cH4B7FkpeDgCkZw8VGmAAA=="),
  "offsite-2026-03": photo("offsite-2026-03", 2000, 1333, "A team member speaking at the podium at the 2026 offsite", "Offsite 2026/JUN04898.JPG", "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAAsBMJYgCdAEWDTs5wHegAP0Bdxd+6XKnarP9qTiizFklxzDVIiLHjUunfVk3Nlh6zE8kcRF624wHJ3Mjv+kUYz0U1S4uoAAA"),
  "offsite-2026-04": photo("offsite-2026-04", 2000, 1333, "The team laughing as a colleague is handed a caricature trophy", "Offsite 2026/JUN04967.JPG", "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwAgCdASoQAAsAAsBMJZwC7AYstWCSWNI4AAD+NHQnodwxq56yqU0KkFUcdgf+LqpHdsjv/u9n/TGgT5S3QV/RPaszglAqjRONMk+eqd5++8vMoT9tTQINggYtCdVEoGlUDp/+AUINPCtR2vXLr5n6RrswEYtKACD8AAAA"),
  "offsite-2026-05": photo("offsite-2026-05", 2000, 1333, "The whole team posing together indoors at the 2026 offsite", "Offsite 2026/JUN05139.JPG", "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAAsBMJZgCdAEN9cKPqO7YAAD+kbfOubdJALiXFSnv2gPU2je/sn9XIEbkkaSEKHlin4uhRo0uiS1Zaa6rKXzbQZqhlxEADXsNKidsiGAA"),
  "offsite-2026-06": photo("offsite-2026-06", 2000, 1333, "The whole team gathered outdoors under the trees at the 2026 offsite", "Offsite 2026/JUN05273.JPG", "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAsAAsBMJYwAAtDbl6OtkAD+sQzTahTCYW8LfCshBm3tWm1vud47x6g9Ga94eM41iuYWyJyOboiGvQyLr1w1gzqrO2/+UpJHNQjfPX/5+Dxn5AA="),
  "offsite-2026-07": photo("offsite-2026-07", 1200, 1600, "A team selfie by the water at the 2026 offsite", "Offsite 2026/WhatsApp Image 2026-10-02 at 11.52.46 AM.jpeg", "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAACQBACdASoQABUAPtFUo0uoJKMhsAgBABoJZgC7AYu4zYK76cG02GmGNCJVOwAA/rQr323CJd92fWMdkTbTw6c7+tYQ1JT9hL51VeUqMEMv8rCUhctLiRwHm31y54DnNgM9cetmMQwd2HV3wd4u19UpXUoYGFWY0+yOCyjNomyJczWCupq0L5Qfn7cIz6X34MsK3jzsh5356FndfQP8ppcOY+i/0d3IZuVdRZXU1IzfmWl1RcKFoFG4RxLWk/qKtmk9MP/kaXVS4SEmewF2aYAA"),
  "recognition-indhu": photo("recognition-indhu", 2000, 1333, "Indhu receiving her trophy", "Indhu - Recognization.JPG", "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAAsBMJZwAAubgLW9aQAD+6FHYHng9AkHvBKt1QlwOuh2IIw7t8kJ34/FxDfAKzC00ZfbKQrdYWSMWPzwljhZXqAAA"),
  "recognition-namitha": photo("recognition-namitha", 2000, 1333, "Namitha holding up her trophy with colleagues", "Namitha - Recognization.JPG", "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAAsBMJZwC7ADcJm94pVQAAPzV2HHDoRbbNXEB2E2aZMDPumeLeyqZWyewajFOlljIC1YCbLfe0va5e1cfiUBTX/3snI8mh62dqRDDJo81AOAAAA=="),
  "recognition-rajesh": photo("recognition-rajesh", 2000, 1333, "Rajesh holding up his trophy with guests beside him", "Rajesh - Recognization.JPG", "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAsAAsBMJZwAAuawtJ74MAD+63m98aH95jeNqWhsGurVNROG207qWUXYjsvU3Dle+bmSzVBnOyyb07fFRlmf6BZ0xnqecboOqvvoUAA="),
  "recognition-vignesh": photo("recognition-vignesh", 2000, 1333, "Vignesh receiving his trophy", "Vignesh - Recognization.JPG", "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAsAAsBMJZwAAubhmUtlgAD+1z9c21HCkibXxyddViCJA7C166G3X1+s+3cLMjtfr4lGFfG+n9GMiOON1aZ3SWQcBtdUGQd3hcp4tciisQgA"),
  "recognition-team-trophies": photo("recognition-team-trophies", 2000, 1333, "The team outdoors behind a table of trophies", "Recognization.JPG", "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAwAgCdASoQAAsAAsBMJZQC7AYvrdYFYsdPAAD+anyeYGS8YhfcMu/iMVoy4vh43Vz7vA78+tJcFj7c+z1sESDwgVUB4IPbllFSvDvIsylrIb3J6MV90UrsCwMp/otHWQsRcBkCLZrj61JJqU5wDLt4caAAAA=="),
  "recognition-medals-01": photo("recognition-medals-01", 2000, 1333, "Team members wearing their medals, with a young guest", "JUN04817.JPG", "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAsAAsBMJZwC7AEOwsetJ1AA/tc/iCsSrP2mND91bSkxUMJeuKnSSjU7GFdE7S0AjmVqonC0G5E81fsGppN3yTDhV6FROicwAA=="),
  "recognition-medals-02": photo("recognition-medals-02", 2000, 1333, "A row of team members wearing their medals", "JUN04842.JPG", "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAQCdASoQAAsAAsBMJQAAXOLRUsPAAP7yZe/2GWeZo5Q997clXax+mvc/oZfAStqUPbi/dPKuXIqk5sNFGAL60GSdpYu61hc16qWQB9Tof/gnCR+vwZiPcAA="),
} as const satisfies Record<string, AboutPhoto>;

export type AboutPhotoKey = keyof typeof PHOTOS;
