/**
 * Home v2 — layout data.
 *
 * **This file no longer restates a single line of copy.** Every string comes
 * from `lib/home-content.ts`, the same module the main home page renders
 * from, and this file only adds what is genuinely v2's: which photograph a
 * card uses, which cell is filled amber, which engagement opens first.
 *
 * That is a change from the first cut, and the reason is the obvious one. v2
 * originally held its own copy of the client's copy, and the two drifted
 * almost immediately — v2 was still running the untrimmed 27-word hero lead
 * that v1 had cut to two thirds, plus a paragraph transcribed off the design
 * comp that the copy document never contained. A second copy of the copy is
 * how one of them goes stale, exactly as a second copy of a phone number is.
 * The same argument already governs `CONTACT` and `OFFICES` in the footer.
 *
 * So: the COMP governs layout, `home-content.ts` governs words. Change the
 * copy in one place and both versions move together.
 *
 * What is still local to this file, and why:
 *
 *   images     which frame sits on which card. A property of this layout —
 *              v1 uses a different set in different places
 *   tone       which cells are filled amber, blue, or left white. Design
 *   featured   which engagement is open on arrival. Design
 *   nav        v2 renders its own header, though every destination is the
 *              signed-off sitemap's
 *   footer     the lockup line and the column headings, which are structure
 *              rather than prose
 */

import {
  ABOUT,
  CASE_STUDIES,
  CLOSING,
  HERO,
  IMPACT,
  LOGOS,
  MODELS,
  RESULTS,
  SERVICES,
  TESTIMONIALS,
} from "@/lib/home-content";

/* 01 — hero -------------------------------------------------------------- */
export const V2_HERO = {
  eyebrow: HERO.eyebrow,
  /**
   * The comp breaks the headline after "expertise.". v1 splits the same
   * sentence at a different point so its second half can carry the brand
   * amber against a dark ground — here the ground is white, where #FEC00F
   * measures 1.65:1 and can never be type, so the two halves are rejoined
   * and the break moves to the comp's.
   */
  titleA: HERO.titleA,
  titleB: `${HERO.titleB}${HERO.titleAccent}`,
  lead: HERO.lead,
  kicker: HERO.kicker,
  cta: HERO.cta,
  trust: HERO.trust,
  quote: HERO.quote,
  media: {
    src: "/hero/meeting.png",
    alt: "Consultants working together around a table in a meeting room",
  },
} as const;

/* 02 — client strip ------------------------------------------------------ */
/**
 * The thirteen supplied marks, straight from `LOGOS`. `scale` there is a
 * height multiplier measured per FILE by `scripts/inkscale.mjs` — a property
 * of the files, not of a layout, which is why the same numbers hold in both
 * versions.
 *
 * The FILES differ: v2 draws from `public/clients-light/`, generated by
 * `scripts/logos-light.mjs`, because the originals are painted white for v1's
 * dark hero band and render as nothing on a white page.
 */
export const V2_LOGOS = {
  label: HERO.trust,
  dir: "/clients-light",
  items: LOGOS.items,
} as const;

/* 03 — about ------------------------------------------------------------- */
export const V2_ABOUT = {
  eyebrow: ABOUT.eyebrow,
  body: ABOUT.body,
  stat: ABOUT.stat,
  statSuffix: ABOUT.statSuffix,
  statTail: ABOUT.statTail,
  /**
   * FOUR points now, against three supplied marks — the copy gained
   * "Enterprise-Ready Integrations" and `home-content.ts` deliberately leaves
   * its `icon` off rather than reusing one of the other three. So `icon` is
   * read defensively here and the component falls back to a drawn glyph.
   *
   * `filled` is derived from the FILE, not from a position in the array. The
   * supplied marks have their stroke colour baked in rather than using
   * `currentColor`, and `2nd.svg` is drawn in WHITE because it is meant to
   * sit on a filled disc — reorder the array and this still puts the white
   * icon on the only ground it can be seen against.
   */
  points: ABOUT.points.map((point) => {
    const icon = "icon" in point ? point.icon : undefined;
    return { ...point, icon, filled: icon === "/2nd.svg" };
  }),
} as const;

/* 04 — impact ------------------------------------------------------------ */
export const V2_IMPACT = {
  eyebrow: IMPACT.eyebrow,
  titleLead: IMPACT.titleLead,
  titleRest: IMPACT.titleAccent,
  body: IMPACT.body,
  cta: IMPACT.cta,
  media: {
    /* Client-supplied. Corners are already rounded in the file. */
    src: "/sections/impact.png",
    alt: "Two consultants reviewing a Workday environment on a laptop",
    tag: IMPACT.mediaTag,
  },
  /**
   * The four cards carry the figures the main home page carries.
   *
   * There is no `source` on them any more and none is invented: the previous
   * four figures were all traceable to one engagement and `home-content.ts`
   * dropped the attribution when the client replaced them, because carrying
   * the old source forward would attribute new figures to a client who never
   * stated them. `statLabel` sits where `source` used to.
   */
  cards: IMPACT.cards.map((card, i) => ({
    ...card,
    tone: i % 2 === 0 ? ("primary" as const) : ("accent" as const),
  })),
} as const;

/* 05 — services ---------------------------------------------------------- */
/** The seven, in the document's order. Only six are routes: AMS is an
    engagement model, so its card points at `/what-we-do#workday-ams`. */
const SERVICE_IMAGES = [
  "/services/service-1.png",
  "/services/service-2.png",
  "/services/service-3.png",
  "/services/service-4.png",
  "/services/service-5.png",
  "/services/service-6.png",
  "/services/service-7.png",
] as const;

export const V2_SERVICES = {
  eyebrow: SERVICES.eyebrow,
  title: SERVICES.title,
  items: SERVICES.items.map((item, i) => ({
    ...item,
    /* Falls back to the first frame rather than `undefined` if a service is
       ever added without one — a missing `src` throws in next/image. */
    image: SERVICE_IMAGES[i] ?? SERVICE_IMAGES[0],
  })),
} as const;

/* 06 — global Workday capability ---------------------------------------- */
/**
 * Formerly four counters — 20+, 200+, 40+, 100%. The client moved those
 * figures UP into the heading, where they now open the section, and replaced
 * the cards with four capabilities. So this band no longer counts anything:
 * the figure in each cell is the item's own index.
 *
 * The comp's strip survives the change intact, which is the point of taking
 * layout from the comp and words from `home-content.ts` — the cells did not
 * care what number was in them.
 */
export const V2_RESULTS = {
  eyebrow: RESULTS.eyebrow,
  titleLead: RESULTS.titleLead,
  titleRest: RESULTS.titleRest,
  body: RESULTS.body,
  cta: HERO.cta,
  /**
   * The comp fills the first cell amber and the third blue and leaves the
   * other two white. `RESULTS.items` carries its own `tone` — three blue and
   * amber on the last — which is v1's scene, where the cells are separate
   * cards with a coloured rule each. In the comp's JOINED strip four
   * saturated cells out of four is a block of colour rather than a rhythm, so
   * the fill pattern is the comp's and the data's `tone` is left to v1.
   */
  items: RESULTS.items.map((item, i) => ({
    ...item,
    /* `highlight` exists on exactly one item — the client's own "40+
       countries", the one hard figure left in the cards. Read defensively so
       the other three do not need the key. */
    highlight: "highlight" in item ? item.highlight : undefined,
    fill: i === 0 ? ("accent" as const) : i === 2 ? ("primary" as const) : ("plain" as const),
  })),
} as const;

/* 07 — use cases --------------------------------------------------------- */
const CASE_IMAGES = [
  "/comp/section-08.webp",
  "/comp/section-07.webp",
  "/comp/section-02.webp",
] as const;

/**
 * `home-content.ts` already says it: **there is no case-study page.** These
 * three are the whole record, so the card carries everything and offers no
 * way out of itself — a "read more" that goes nowhere is worse than not
 * having one. v2 had such a link and it has been removed.
 *
 * `capabilities` is the client's own list and becomes the chips on the open
 * card. `impact` is what the reader came for and is visible on every card;
 * `challenge` and `approach` are the story behind it and sit behind the
 * toggle. That split is `home-content.ts`'s decision, kept.
 */
export const V2_CASES = {
  eyebrow: CASE_STUDIES.eyebrow,
  title: CASE_STUDIES.title,
  body: CASE_STUDIES.body,
  items: CASE_STUDIES.items.map((item, i) => ({
    ...item,
    image: CASE_IMAGES[i] ?? CASE_IMAGES[0],
    /* The comp opens the last one. */
    featured: i === CASE_STUDIES.items.length - 1,
  })),
  labels: {
    challenge: "Business challenge",
    approach: "Hazeberg solution",
  },
} as const;

/* 08 — engagement models ------------------------------------------------- */
export const V2_MODELS = {
  eyebrow: MODELS.eyebrow,
  title: MODELS.title,
  body: MODELS.body,
  /* The comp fills the middle card amber. Design. */
  items: MODELS.items.map((item, i) => ({ ...item, featured: i === 1 })),
  cta: MODELS.cta,
  bestForLabel: "Best for",
} as const;

/* 09 — testimonials ------------------------------------------------------ */
/**
 * The comp shows two cards, and there are exactly two APPROVED quotes — so
 * the four marked `placeholder` in `TESTIMONIALS.items` are filtered out
 * rather than the list being trimmed to a count. The section then grows on
 * its own the day real quotes replace them, and it cannot ever ship a
 * fabricated one by accident.
 *
 * Client note on the source document: use client-approved quotes only.
 */
export const V2_TESTIMONIALS = {
  eyebrow: TESTIMONIALS.eyebrow,
  title: TESTIMONIALS.title,
  items: TESTIMONIALS.items.filter((item) => !("placeholder" in item && item.placeholder)),
} as const;

/* 10 — closing ----------------------------------------------------------- */
export const V2_CLOSING = {
  eyebrow: CLOSING.eyebrow,
  title: CLOSING.title,
  body: CLOSING.body,
  cta: CLOSING.cta,
  media: { src: "/comp/section-14.webp", alt: "" },
} as const;

/* 11 — navigation -------------------------------------------------------- */
/**
 * v2 carries its own header, but every destination is the signed-off
 * sitemap's, identical to what `lib/navigation.ts` resolves to. The comp's
 * bar shows five items and one button, which is what this is.
 *
 * `menu` is present on EVERY item, explicitly `undefined` on the two with no
 * dropdown. Omitting the key makes the array a union of two shapes, and
 * `link.menu` then fails to typecheck on the members that lack it.
 */
export const V2_NAV = {
  links: [
    { label: "Services", href: "/what-we-do", menu: "services" },
    { label: "What we do", href: "/what-we-do", menu: "solutions" },
    { label: "About", href: "/about", menu: "about" },
    { label: "Berg", href: "/berg", menu: undefined },
    { label: "Careers", href: "/careers", menu: undefined },
  ],
  cta: { label: "Contact us", href: "/contact" },
} as const;

/* 12 — footer ------------------------------------------------------------ */
/**
 * Structure, not prose. The link labels come from `SERVICES.items`, so a
 * service added to the copy document appears in the footer without anyone
 * remembering to add it.
 *
 * The addresses, the phone number and the email are not here either —
 * `Footer` imports `CONTACT` and `OFFICES` from `lib/navigation.ts`, the
 * site's single source of truth for them.
 *
 * What is NOT here: the comp's bottom-left line reads as a DPIIT
 * recognition. It is not in the copy document, the comp is not legible
 * enough to transcribe the wording, and a government certification is the
 * last claim to reconstruct from a blurry render. Listed in
 * `V2-CHECKLIST.md` for the client to supply verbatim.
 */
export const V2_FOOTER = {
  lockupLead: "Workday expertise",
  /** The amber half. On the footer's near-black ground #FEC00F measures
      11.26:1; on the white page above it, 1.65:1 — which is why this is the
      only place on the page it carries a word. */
  lockupAccent: "that stays engaged",
  columns: [
    {
      title: "Services",
      links: SERVICES.items.slice(0, 4).map((s) => ({ label: s.label, href: s.href })),
    },
    {
      title: "",
      links: SERVICES.items.slice(4).map((s) => ({ label: s.label, href: s.href })),
    },
    {
      title: "Company",
      links: [
        { label: "What we do", href: "/what-we-do" },
        { label: "About us", href: "/about" },
        { label: "Berg", href: "/berg" },
        { label: "Careers", href: "/careers" },
        { label: "Contact", href: "/contact" },
      ],
    },
  ],
  talkLabel: "Talk to us",
  legal: "© 2026 Hazeberg Consulting. All rights reserved.",
} as const;
