"use client";

import { V2_LOGOS } from "@/lib/v2/content";

/**
 * The client strip.
 *
 * The comp shows a single static row. This runs the same marks as a very slow
 * rail instead, for one reason that is not taste: there are THIRTEEN supplied
 * marks and the comp's row fits about ten. Dropping three so the picture
 * matches would be choosing which clients to hide; a rail shows all of them
 * and still occupies one band.
 *
 * It is slow enough to read as a static row at a glance — 90 seconds for a
 * full pass — and it PAUSES under the pointer, so anyone who wants to look at
 * a particular mark can. A strip that keeps sliding while you try to read it
 * is the reason most logo rails are annoying.
 *
 * Marks come from `public/clients-light/`, generated by
 * `scripts/logos-light.mjs`. The originals in `public/clients/` are painted
 * white for v1's dark hero band and render as nothing here. A CSS filter
 * cannot substitute: `brightness-0` would flatten the mark AND its knockouts
 * to the same black, filling in the UPS shield and the DocuSign tile.
 *
 * Opacity 55% at rest, 100% under the pointer. Thirteen marks at full
 * strength would be the loudest band on a page whose whole argument is
 * restraint.
 */

/** One pass. Rendered twice so the -50% loop has something to run into;
    `aria-hidden` on the copy keeps thirteen marks from being announced
    twenty-six times. */
function Track({ hidden = false }: { hidden?: boolean }) {
  return (
    <ul aria-hidden={hidden || undefined} className="flex shrink-0 items-center">
      {V2_LOGOS.items.map((logo) => (
        <li key={logo.file} className="shrink-0 px-7 sm:px-9">
          {/*
            A plain img, not next/image: these are vectors, so there is nothing
            for the optimiser to do and `fill` would force a fixed box around
            thirteen very different aspect ratios.

            Height, not `transform: scale`. A transform leaves the layout box
            at its unscaled size, so a mark pulled back to half size would
            still reserve full-size space and the rail's rhythm would break.
            The `scale` factors are measured per file by `scripts/inkscale.mjs`
            — do not hand-tune them.
          */}
          {/*
            NOT lazy. Ten of these thirteen sit outside the viewport
            HORIZONTALLY, inside a rail that is 90 seconds from bringing them
            on screen — the browser's lazy heuristic never fires for them, so
            they stayed undecoded and then popped in one at a time as the rail
            travelled. Measured: 10 of 13 images with `naturalWidth === 0`
            after a full scroll of the page. They are SVG wordmarks averaging
            a couple of kB; eager is both correct and cheap.
          */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`${V2_LOGOS.dir}/${logo.file}`}
            alt={hidden ? "" : logo.name}
            decoding="async"
            className="w-auto opacity-55 transition-opacity duration-300 hover:opacity-100"
            style={{ height: `calc(1.75rem * ${logo.scale})` }}
          />
        </li>
      ))}
    </ul>
  );
}

export function LogoStrip() {
  return (
    <section
      aria-label={V2_LOGOS.label}
      className="v2-marquee-host relative border-y border-border bg-canvas py-9"
    >
      <div className="v2-fade-x overflow-hidden">
        <div className="v2-marquee flex w-max" style={{ animationDuration: "90s" }}>
          <Track />
          <Track hidden />
        </div>
      </div>
    </section>
  );
}
