/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  challenge: string;
  approach: string;
  impact: Array<string>;
  capabilities: Array<string>;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    standIn?: boolean;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: {
    titleA: string;
    titleB: string;
    titleAccent: string;
    lead: string;
    cta: {
      label: string;
      href:
        | "/contact"
        | "/about"
        | "/what-we-do"
        | "/berg"
        | "/careers"
        | "/services/workday-hcm"
        | "/services/workday-payroll"
        | "/services/workday-financials"
        | "/services/workday-integrations"
        | "/services/workday-reporting-analytics"
        | "/what-we-do#workday-ams"
        | "/services/workday-extend";
    };
    trust: string;
  };
  about: {
    eyebrow: string;
    stat: number;
    statSuffix?: string;
    statTail: string;
    body: string;
    cta: {
      label: string;
      href:
        | "/contact"
        | "/about"
        | "/what-we-do"
        | "/berg"
        | "/careers"
        | "/services/workday-hcm"
        | "/services/workday-payroll"
        | "/services/workday-financials"
        | "/services/workday-integrations"
        | "/services/workday-reporting-analytics"
        | "/what-we-do#workday-ams"
        | "/services/workday-extend";
    };
    points: Array<{
      title: string;
      body: string;
      _type: "point";
      _key: string;
    }>;
  };
  impact: {
    eyebrow: string;
    titleLead: string;
    titleAccent: string;
    body: string;
    cta: {
      label: string;
      href:
        | "/contact"
        | "/about"
        | "/what-we-do"
        | "/berg"
        | "/careers"
        | "/services/workday-hcm"
        | "/services/workday-payroll"
        | "/services/workday-financials"
        | "/services/workday-integrations"
        | "/services/workday-reporting-analytics"
        | "/what-we-do#workday-ams"
        | "/services/workday-extend";
    };
    cards: Array<{
      stat: string;
      statLabel: string;
      title: string;
      body: string;
      placeholder?: boolean;
      _type: "impactCard";
      _key: string;
    }>;
  };
  services: {
    eyebrow: string;
    title: string;
    items: Array<{
      service:
        | "hcm"
        | "payroll"
        | "financials"
        | "integrations"
        | "reporting-analytics"
        | "ams"
        | "extend";
      label: string;
      body: string;
      cta: string;
      _type: "serviceItem";
      _key: string;
    }>;
  };
  results: {
    eyebrow: string;
    titleLead: string;
    titleRest: string;
    body: string;
    items: Array<{
      title: string;
      body: string;
      highlight?: string;
      _type: "capability";
      _key: string;
    }>;
    media: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      standIn?: boolean;
      _type: "image";
    };
  };
  caseStudies: {
    eyebrow: string;
    title: string;
    body: string;
    items: Array<
      {
        _key: string;
      } & CaseStudyReference
    >;
  };
  models: {
    eyebrow: string;
    title: string;
    body: string;
    cta: string;
    items: Array<{
      stage: string;
      title: string;
      body: string;
      bestFor: string;
      href:
        | "/contact"
        | "/about"
        | "/what-we-do"
        | "/berg"
        | "/careers"
        | "/services/workday-hcm"
        | "/services/workday-payroll"
        | "/services/workday-financials"
        | "/services/workday-integrations"
        | "/services/workday-reporting-analytics"
        | "/what-we-do#workday-ams"
        | "/services/workday-extend";
      image: {
        asset: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        standIn?: boolean;
        _type: "image";
      };
      _type: "model";
      _key: string;
    }>;
  };
  testimonials: {
    eyebrow: string;
    title: string;
    items: Array<{
      body: string;
      role: string;
      name: string;
      portrait?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        standIn?: boolean;
        _type: "image";
      };
      placeholder?: boolean;
      _type: "testimonial";
      _key: string;
    }>;
  };
  closing: {
    eyebrow: string;
    title: string;
    body: string;
    cta: {
      label: string;
      href:
        | "/contact"
        | "/about"
        | "/what-we-do"
        | "/berg"
        | "/careers"
        | "/services/workday-hcm"
        | "/services/workday-payroll"
        | "/services/workday-financials"
        | "/services/workday-integrations"
        | "/services/workday-reporting-analytics"
        | "/what-we-do#workday-ams"
        | "/services/workday-extend";
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CaseStudy
  | SanityImageCrop
  | SanityImageHotspot
  | CaseStudyReference
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{  hero{ titleA, titleB, titleAccent, lead, cta{ label, href }, trust },  about{    eyebrow, stat, statSuffix, statTail, body, cta{ label, href },    points[]{ title, body }  },  impact{    eyebrow, titleLead, titleAccent, body, cta{ label, href },    cards[]{ stat, statLabel, title, body }  },  services{ eyebrow, title, items[]{ service, label, body, cta } },  results{    eyebrow, titleLead, titleRest, body,    items[]{ title, body, highlight },    media{   alt,  crop,  hotspot,  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height } }  },  caseStudies{    eyebrow, title, body,    items[]->{ title, challenge, approach, impact, capabilities, image{   alt,  crop,  hotspot,  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height } } }  },  models{    eyebrow, title, body, cta,    items[]{ stage, title, body, bestFor, href, image{   alt,  crop,  hotspot,  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height } } }  },  testimonials{ eyebrow, title, items[]{ body, name, role, portrait{   alt,  crop,  hotspot,  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height } } } },  closing{ eyebrow, title, body, cta{ label, href } }}
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    titleA: string;
    titleB: string;
    titleAccent: string;
    lead: string;
    cta: {
      label: string;
      href:
        | "/about"
        | "/berg"
        | "/careers"
        | "/contact"
        | "/services/workday-extend"
        | "/services/workday-financials"
        | "/services/workday-hcm"
        | "/services/workday-integrations"
        | "/services/workday-payroll"
        | "/services/workday-reporting-analytics"
        | "/what-we-do"
        | "/what-we-do#workday-ams";
    };
    trust: string;
  };
  about: {
    eyebrow: string;
    stat: number;
    statSuffix: string | null;
    statTail: string;
    body: string;
    cta: {
      label: string;
      href:
        | "/about"
        | "/berg"
        | "/careers"
        | "/contact"
        | "/services/workday-extend"
        | "/services/workday-financials"
        | "/services/workday-hcm"
        | "/services/workday-integrations"
        | "/services/workday-payroll"
        | "/services/workday-reporting-analytics"
        | "/what-we-do"
        | "/what-we-do#workday-ams";
    };
    points: Array<{
      title: string;
      body: string;
    }>;
  };
  impact: {
    eyebrow: string;
    titleLead: string;
    titleAccent: string;
    body: string;
    cta: {
      label: string;
      href:
        | "/about"
        | "/berg"
        | "/careers"
        | "/contact"
        | "/services/workday-extend"
        | "/services/workday-financials"
        | "/services/workday-hcm"
        | "/services/workday-integrations"
        | "/services/workday-payroll"
        | "/services/workday-reporting-analytics"
        | "/what-we-do"
        | "/what-we-do#workday-ams";
    };
    cards: Array<{
      stat: string;
      statLabel: string;
      title: string;
      body: string;
    }>;
  };
  services: {
    eyebrow: string;
    title: string;
    items: Array<{
      service:
        | "ams"
        | "extend"
        | "financials"
        | "hcm"
        | "integrations"
        | "payroll"
        | "reporting-analytics";
      label: string;
      body: string;
      cta: string;
    }>;
  };
  results: {
    eyebrow: string;
    titleLead: string;
    titleRest: string;
    body: string;
    items: Array<{
      title: string;
      body: string;
      highlight: string | null;
    }>;
    media: {
      alt: string;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      asset: {
        url: string;
        width: number | null;
        height: number | null;
      };
    };
  };
  caseStudies: {
    eyebrow: string;
    title: string;
    body: string;
    items: Array<{
      title: string;
      challenge: string;
      approach: string;
      impact: Array<string>;
      capabilities: Array<string>;
      image: {
        alt: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          url: string;
          width: number | null;
          height: number | null;
        };
      };
    }>;
  };
  models: {
    eyebrow: string;
    title: string;
    body: string;
    cta: string;
    items: Array<{
      stage: string;
      title: string;
      body: string;
      bestFor: string;
      href:
        | "/about"
        | "/berg"
        | "/careers"
        | "/contact"
        | "/services/workday-extend"
        | "/services/workday-financials"
        | "/services/workday-hcm"
        | "/services/workday-integrations"
        | "/services/workday-payroll"
        | "/services/workday-reporting-analytics"
        | "/what-we-do"
        | "/what-we-do#workday-ams";
      image: {
        alt: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          url: string;
          width: number | null;
          height: number | null;
        };
      };
    }>;
  };
  testimonials: {
    eyebrow: string;
    title: string;
    items: Array<{
      body: string;
      name: string;
      role: string;
      portrait: {
        alt: string | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        asset: {
          url: string;
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    }>;
  };
  closing: {
    eyebrow: string;
    title: string;
    body: string;
    cta: {
      label: string;
      href:
        | "/about"
        | "/berg"
        | "/careers"
        | "/contact"
        | "/services/workday-extend"
        | "/services/workday-financials"
        | "/services/workday-hcm"
        | "/services/workday-integrations"
        | "/services/workday-payroll"
        | "/services/workday-reporting-analytics"
        | "/what-we-do"
        | "/what-we-do#workday-ams";
    };
  };
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "homePage" && _id == "homePage"][0]{\n  hero{ titleA, titleB, titleAccent, lead, cta{ label, href }, trust },\n  about{\n    eyebrow, stat, statSuffix, statTail, body, cta{ label, href },\n    points[]{ title, body }\n  },\n  impact{\n    eyebrow, titleLead, titleAccent, body, cta{ label, href },\n    cards[]{ stat, statLabel, title, body }\n  },\n  services{ eyebrow, title, items[]{ service, label, body, cta } },\n  results{\n    eyebrow, titleLead, titleRest, body,\n    items[]{ title, body, highlight },\n    media{ \n  alt,\n  crop,\n  hotspot,\n  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height }\n }\n  },\n  caseStudies{\n    eyebrow, title, body,\n    items[]->{ title, challenge, approach, impact, capabilities, image{ \n  alt,\n  crop,\n  hotspot,\n  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height }\n } }\n  },\n  models{\n    eyebrow, title, body, cta,\n    items[]{ stage, title, body, bestFor, href, image{ \n  alt,\n  crop,\n  hotspot,\n  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height }\n } }\n  },\n  testimonials{ eyebrow, title, items[]{ body, name, role, portrait{ \n  alt,\n  crop,\n  hotspot,\n  "asset": asset->{ url, "width": metadata.dimensions.width, "height": metadata.dimensions.height }\n } } },\n  closing{ eyebrow, title, body, cta{ label, href } }\n}': HOME_PAGE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
